# Generated by Django 3.0.2 on 2020-02-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_assets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='assets',
        ),
        migrations.DeleteModel(
            name='media',
        ),
        migrations.DeleteModel(
            name='UploadModel',
        ),
    ]
